apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki 
  namespace: openshift-logging 
spec:
  managementState: Managed
  limits:
    global: 
      retention: 
        days: 20 # Set the value as per requirement
  size: 1x.extra-small 
  storage:
    schemas:
    - version: v13
      effectiveDate: 2025-12-12
    secret:
      name: logging-bucket
      type: s3 
  storageClassName: managed-csi
  tenants:
    mode: openshift-logging 
